version: '3.9'

services:
  server:
    build: 
      context: ./server
    image: gurkirat2000/server:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
    - db
  db:
    image: "postgres"
    ports: 
      - "4444:5432"
    
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: recipe_db
  client:
    build:
      context: ./client
    image: gurkirat2000/client:latest
    ports:
      - "3000:80"
    depends_on:
      - server
