name: CI Pipeline for Client and Server

on:
  pull_request:
    branches:
      - master

jobs:
  backend-build:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print working directory
      run: pwd

    - name: List files in root directory
      run: ls -la

    - name: List files in server directory
      run: ls -la ./server

    - name: Set up Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: '18.17'

    - name: Install Backend Dependencies
      run: npm install
      working-directory: ./server

  frontend-build:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print working directory
      run: pwd

    - name: List files in root directory
      run: ls -la

    - name: List files in client directory
      run: ls -la ./client

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18.17'

    - name: Install Frontend Dependencies
      run: npm install
      working-directory: ./client
