name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push server image
      working-directory: ./server
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/recipe-app-server:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/recipe-app-server:latest

    - name: Build and push client image
      working-directory: ./client
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/recipe-app-client:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/recipe-app-client:latest

    - name: Deploy with docker-compose
      run: docker-compose up -d
